
services:
  
  # Postgres database service for Keycloak
  postgres:
    image: postgres:16.2
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - shopnest-net

  # Keycloak service for authentication and authorization
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: keycloak-server
    environment:
      TZ: Europe/Berlin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: |
       start-dev --http-port 7080 --db postgres --features token-exchange --db-url jdbc:postgresql://postgres/${POSTGRES_DB} --db-username ${POSTGRES_USER} --db-password ${POSTGRES_PASSWORD} --import-realm
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    ports:
      - "7080:7080"
      - "7443:7443"
    depends_on:
      - postgres
    networks:
      - shopnest-net

networks:
  shopnest-net:
    driver: bridge

volumes:
  keycloak_data:
  