########################################### Database Properties ###########################################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://mysql-service:3306/shopnest-db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: "jdbc:mysql://shopnest-server.mysql.database.azure.com:3306/shopnest-db?useSSL=true"
    username: shopnest_usr
    password: ShopNest_pwd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
########################################### Security Properties ###########################################
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: shopnest-client
            client-secret: VZyb5xZ54qCppMeToTFFmn8w9a8wUofP
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:7080/realms/master
            user-info-uri: http://localhost:7080/realms/master/protocol/openid-connect/userinfo
            token-uri: http://localhost:7080/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:7080/realms/master/protocol/openid-connect/auth
