#spring.application.name=shopnest-api
server:
  port: 8080

spring:
  application.name: shopnest-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://backend-keycloak-auth:8082/realms/shopnest
