############# Database Properties ###########################################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://mysql-service:3306/shopnest-db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: "jdbc:mysql://shopnest-server.mysql.database.azure.com:3306/shopnest-db?useSSL=true"
    username: shopnest_usr
    password: ShopNest_pwd
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: okta-client-id
            client-secret: okta-client-secret
        provider:
          keycloak:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
############ Keycloak Properties #####################
