#spring.application.name=shopnest-gateway
server:
  port: 8081

spring:
  application.name: shopnest-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: shopnest-api
          uri: lb://shopnest-api
          predicates:
            - Path=/api/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://backend-keycloak-auth:8082/realms/shopnest-keycloak